### ISSUE TITLE
CSS typo error

### ISSUE THREAD

**Issue by cboillat** [HugoGiraudel/hugogiraudel.github.com#16]
in partial _nav.scss line 50 :
box-shadow: 0 -3**spx** 5px -3px rgba(black, 0.2);

**Comment by HugoGiraudel** [comment]
Woops, thanks. :)

**Comment by cboillat** [comment]
De rien ;) bonne fin de journée 


     On Monday, May 25, 2015 3:46 PM, Hugo Giraudel <notifications@github.com> wrote:
   

 Woops, thanks. :)—
